Default: &defaults
  engine: Sqlite
  database: Yiki.sqlite3

Development:
  <<: *defaults

Test:
  engine: Sqlite
  database: Yiki_test.sqlite3
  <<: *defaults

Staging:
  enigne: Postgresql
  user: yiki
  password: yiki
  host: localhost
  port: 5432
  database: yiki_staging
  <<: *defaults

Production:
  engine: Postgresql
  user: yiki
  password: yiki
  host: localhost
  port: 5432
  database: yiki_production
  <<: *defaults